stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/diabetes.csv
    outs:
    - data/raw/diabetes.csv
  
  sampled_data:
    cmd: python src/data_sampler.py --config=params.yaml
    deps:
    - src/load_data.py
    - data/raw/diabetes.csv
    outs:
    - data/processed/oversampled_diabetes.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/data_sampler.py
    - data/processed/oversampled_diabetes.csv
    outs:
    - data/processed/train_diabetes.csv
    - data/processed/test_diabetes.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_diabetes.csv
    - data/processed/test_diabetes.csv 
    - src/train_and_evaluate.py
    params:
    - estimators.XGBClassifier.learning_rate
    - estimators.XGBClassifier.max_depth
    - estimators.XGBClassifier.n_estimators
    - estimators.XGBClassifier.min_child_weight
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/model.joblib