base:
  project: diabetes-predicion-project
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: data_given/diabetes.csv

load_data:
  raw_dataset_csv: data/raw/diabetes.csv

sampled_data:
  oversampled_dataset_csv: data/processed/oversampled_diabetes.csv

split_data:
  train_path: data/processed/train_diabetes.csv
  test_path: data/processed/test_diabetes.csv
  test_size: 0.2

estimators:
  XGBClassifier:
    learning_rate: 0.13333333333333333
    max_depth: 5 
    n_estimators: 39
    min_child_weight: 1

model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json