base:
  project: diabetes-predicion-project
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: data_given/diabetes.csv

load_data:
  raw_dataset.csv: data/raw/diabetes.csv

split_data:
  train_path: data/processed/train_diabetes.csv
  test_path: data/processed/test_diabetes.csv
  test_size: 0.2

estimators:
  XGBClassifier:
    learning_rate: 0.13333333333333333
    max_depth: 5 
    n_estimators: 39

model_dir: saved_models